name: 'quanteda'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.28
  - ipywidgets=8.1.1
  - python=3.9
  - cookiecutter=2.5.0
  - pip==23.3.2
  - pip:
    - poetry=1.7.1
    - ghp-import==2.1.0
